version: "3.5"
services:
  db:
    container_name: ekiapp_db
    build:
      context: .
      dockerfile: Dockerfile
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ekiapp
      MYSQL_USER: ekiapp
      MYSQL_PASSWORD: ekiapp123