version: '3'

tasks:
  start:
    cmds:
      - docker-compose up -d --build

  delete:
    cmds:
      - docker-compose down

  gqlgen-init:
    cmds:
      - cd graph
      - go run github.com/99designs/gqlgen init

  gqlgen:
    cmds:
      - cd graph
      - gqlgen generate