// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Station struct {
	StationCd       int        `json:"stationCD"`
	StationName     string     `json:"stationName"`
	Address         *string    `json:"address"`
	BeforeStation   *Station   `json:"beforeStation"`
	AfterStation    *Station   `json:"afterStation"`
	TransferStation []*Station `json:"transferStation"`
}
